# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:  
  # aliased to 5.5.9
  - 5.5
   
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit ./app/tests/testcase.php

notifications: # set notification options
  email:
    recipients:
      - lcento@gmail.com
      - lo.rossella@libero.it
